-- 코드를 작성해주세요
# ROOT를 찾고, 2번의 tail을 찾기

SELECT E2.ID FROM ECOLI_DATA E2
JOIN
    (SELECT E.ID FROM ECOLI_DATA E
    JOIN (SELECT *
        FROM ECOLI_DATA 
        WHERE PARENT_ID IS NULL) F
    ON F.ID=E.PARENT_ID) S
ON E2.PARENT_ID=S.ID
ORDER BY E2.ID ASC



