SELECT D.ITEM_ID, D.ITEM_NAME, D.RARITY FROM ITEM_INFO D
INNER JOIN 
    (SELECT A.ITEM_ID 
    FROM ITEM_TREE A
    LEFT JOIN ITEM_TREE B
      ON B.PARENT_ITEM_ID=A.ITEM_ID
    WHERE B.ITEM_ID is null) C
ON C.ITEM_ID=D.ITEM_ID
ORDER BY D.ITEM_ID DESC