-- 코드를 입력하세요

SELECT A.REST_ID,A.REST_NAME,A.FOOD_TYPE,A.FAVORITES,A.ADDRESS,ROUND(B.BSCORE,2) SCORE FROM REST_INFO A
JOIN (SELECT AVG(REVIEW_SCORE) BSCORE, REST_ID FROM REST_REVIEW Group By REST_ID) B 
on A.REST_ID = B.REST_ID
WHERE A.ADDRESS like '서울%'
Order by ROUND(B.BSCORE,2) DESC, A.FAVORITES DESC