SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO P        -- parent info
  ON T.PARENT_ITEM_ID = P.ITEM_ID
JOIN ITEM_INFO I        -- child info
  ON T.ITEM_ID = I.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC;