#ID, GENOTYPE, PARENT_GENOTYPE
#Sorted by ID


Select B.ID, B.GENOTYPE , ECOLI_DATA.GENOTYPE as PARENT_GENOTYPE FROM 
    (Select ID, PARENT_ID, GENOTYPE FROM ECOLI_DATA) as B  
        left join ECOLI_DATA on ECOLI_DATA.ID = B.PARENT_ID
WHERE ECOLI_DATA.ID is not null and ECOLI_DATA.GENOTYPE & B.GENOTYPE = ECOLI_DATA.GENOTYPE
