-- 코드를 작성해주세요
SELECT MAXTABLE.YEAR, MAXTABLE.MAXYEAR-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID FROM 
    ECOLI_DATA E
    JOIN
        (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAXYEAR 
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) MAXTABLE
    ON MAXTABLE.YEAR=YEAR(DIFFERENTIATION_DATE)
ORDER BY MAXTABLE.YEAR ASC, YEAR_DEV ASC