-- 코드를 입력하세요
SELECT C.FLAVOR
FROM
    (SELECT A.SHIPMENT_ID, A.FLAVOR, B.INGREDIENT_TYPE, A.TOTAL_ORDER
     FROM FIRST_HALF A
     JOIN ICECREAM_INFO B
     ON A.FLAVOR=B.FLAVOR
     ) C
WHERE C.INGREDIENT_TYPE='fruit_based' and C.TOTAL_ORDER > 3000
ORDER BY C.TOTAL_ORDER DESC