-- 코드를 작성해주세요
SELECT O1.ID, O2.FISH_NAME, O2.LENGTH
FROM 
    (SELECT A.FISH_NAME, A.FISH_TYPE, MAX(A.LENGTH) AS LENGTH FROM
        (SELECT N.FISH_NAME, I.LENGTH, I.FISH_TYPE FROM FISH_INFO I
        JOIN FISH_NAME_INFO N
        ON I.FISH_TYPE=N.FISH_TYPE) A
    GROUP BY A.FISH_NAME, A.FISH_TYPE) O2
JOIN FISH_INFO O1
ON O1.FISH_TYPE=O2.FISH_TYPE AND O1.LENGTH=O2.LENGTH
ORDER BY ID ASC

